# Generated by Django 4.0.4 on 2022-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('Select a size', 'Select a size'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra large', 'Extra large')], max_length=30, null=True),
        ),
    ]
