# Generated by Django 4.0.4 on 2022-05-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='store.product'),
        ),
    ]
